sudo: required
services:
  - docker

before_install:
  - docker build -t gvimalku/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gvimalku/react-test npm test -- --coverage

after-success:
  - docker build -t gvimalku/multi-client ./client
  - docker build -t gvimalku/multi-nginx ./nginx
  - docker build -t gvimalku/multi-server ./server
  - docker build -t gvimalku/multi-worker ./worker
